/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#e9c400',
        'surface-bright': '#f9f9f9',
        'inverse-surface': '#2f3131',
        'secondary-fixed': '#ffe16d',
        'outline': '#8c7071',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary-fixed-variant': '#474836',
        'on-primary-fixed-variant': '#8e0f28',
        'on-secondary-container': '#6e5c00',
        'on-primary-container': '#ff828a',
        'surface-container-low': '#f3f3f4',
        'surface-variant': '#e2e2e2',
        'background': '#f9f9f9',
        'inverse-primary': '#ffb3b5',
        'on-surface': '#1a1c1c',
        'on-primary': '#ffffff',
        'surface-container': '#eeeeee',
        'primary-fixed-dim': '#ffb3b5',
        'on-tertiary-fixed': '#1b1d0e',
        'on-surface-variant': '#584141',
        'surface': '#f9f9f9',
        'on-secondary-fixed-variant': '#544600',
        'tertiary-fixed-dim': '#c8c8b0',
        'primary-container': '#800020',
        'on-primary-fixed': '#40000b',
        'surface-tint': '#af2b3e',
        'primary-fixed': '#ffdada',
        'on-secondary': '#ffffff',
        'tertiary-container': '#3d3f2d',
        'secondary-container': '#fcd400',
        'secondary': '#705d00',
        'outline-variant': '#e0bfbf',
        'primary': '#570013',
        'surface-dim': '#dadada',
        'surface-container-high': '#e8e8e8',
        'tertiary-fixed': '#e4e4cc',
        'tertiary': '#272919',
        'on-secondary-fixed': '#221b00',
        'on-background': '#1a1c1c',
        'on-tertiary-container': '#a9aa94',
        'inverse-on-surface': '#f0f1f1',
        'on-error': '#ffffff'
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'sm': '12px',
        'container-max': '1280px',
        'md': '24px',
        'gutter': '24px',
        'base': '8px',
        'lg': '48px',
        'xl': '80px',
        'xs': '4px',
        'margin-mobile': '1rem',
        'stack-md': '1rem',
        'stack-sm': '0.5rem',
        'stack-lg': '2rem'
      },
      fontFamily: {
        'body-lg': ['Work Sans'],
        'headline-lg-mobile': ['Manrope'],
        'headline-lg': ['Manrope'],
        'title-md': ['Manrope'],
        'label-md': ['Work Sans'],
        'body-md': ['Work Sans'],
        'display-lg': ['Manrope'],
        'h3': ['Manrope'],
        'label-sm': ['Work Sans'],
        'h1': ['Manrope'],
        'display': ['Manrope'],
        'body-sm': ['Work Sans'],
        'h2': ['Manrope']
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h3': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'h1': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }]
      }
    },
  },
  plugins: [],
}
